SUDO_PASSWORD

diff --git a/.github/workflows/deploy-to-azure.yml b/.github/workflows/deploy-to-azure.yml
--- a/.github/workflows/deploy-to-azure.yml
+++ b/.github/workflows/deploy-to-azure.yml
@@ -111,10 +111,10 @@ jobs:
       - name: Pull and run Docker image on VM
         run: |
           ssh -o StrictHostKeyChecking=no azureuser@${{ env.VM_IP }} << 'EOF'
-            sudo -S docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
-            sudo -S docker pull ghcr.io/${{ github.repository }}/documentdb:latest
-            sudo -S docker rm -f documentdb 2>/dev/null || true
-            sudo -S docker run -p 9712:9712 --name documentdb --restart=on-failure:3 -i ghcr.io/${{ github.repository }}/documentdb
+            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
+            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker pull ghcr.io/${{ github.repository }}/documentdb:latest
+            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker rm -f documentdb 2>/dev/null || true
+            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker run -p 9712:9712 --name documentdb --restart=on-failure:3 -i ghcr.io/${{ github.repository }}/documentdb
           EOF
 # docker run -p 9712:9712 --name documentdb -i ghcr.io/intelligencecompany/documentdb-1/documentdb
       # - name: Pull and run Docker image on VM
